### ISSUE TITLE
Missing rect from dev_info

### ISSUE THREAD

**Issue by thomasp85** [coolbutuseless/devout#1]
The rectangle callback is missing in `dev_info`. Don't know if that also means that it gets ignored as a callback?

**Comment by coolbutuseless** [comment]
AFAIR `devinfo$device_call` information not used to generate/orchestrate any code. It's purely information for the user. 

But `rect` should be in the list. Will add.

**Comment by thomasp85** [comment]
yeah, I think it is just informative... but it made me vary that rect support may be unsupported by accident

**Comment by coolbutuseless** [comment]
Updated `devinfo` to include `rect` in 7cd8bc3f
