### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by diplodata** [coolbutuseless/devout#12]
Alas install is failing on macOS.  Any idea why?

```
> remotes::install_github('coolbutuseless/devout')
Downloading GitHub repo coolbutuseless/devout@HEAD
Error: Failed to install 'devout' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

invoking that diagnostic just gives

```
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

**Comment by coolbutuseless** [comment]
I develop on a mac and have not seen that error.

Could you:

* ensure you have the latest versions of 'remotes' and 'devtools'
* What version of macOS?
* What version of R?

**Comment by diplodata** [comment]
I'm running 
- remotes 2.2.0
- devtools 2.3.2
- macOS 11.0.1
- R 4.0.2

**Comment by diplodata** [comment]
If it sheds any more light the error occurs after a popup dialogue, e.g.

```
> remotes::install_github('coolbutuseless/devoutrgl')
Downloading GitHub repo coolbutuseless/devoutrgl@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                  
2: CRAN packages only                   
3: None                                 
4: processx (3.4.4    -> 3.4.5  ) [CRAN]
5: rlang    (0.4.8    -> 0.4.9  ) [CRAN]
6: rgl      (0.100.54 -> 0.103.5) [CRAN]
```
<img width="829" alt="image" src="https://user-images.githubusercontent.com/25770724/100997634-67344000-3552-11eb-9dcc-613013aeba58.png">

```
Error: Failed to install 'devoutrgl' from GitHub:
  Failed to install 'devout' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```


The error happens with install options `1` and `2`, and with responses `Yes` and `No` to the popup.

**Comment by coolbutuseless** [comment]
A few things to try:

* ensure the Xcode tools are up to date.  in a terminal: ` xcode-select --install `
* update to the latest Rcpp

**Comment by coolbutuseless** [comment]
No action on this for over a year. Closing until there's a new report.
