### ISSUE TITLE
Crashing on Windows

### ISSUE THREAD

**Issue by coolbutuseless** [coolbutuseless/devout#2]
Package seems to compile and work fine on my machine (MacOS) and TravisCI (linux).

According to Appveyor, the package builds cleanly on Windows, but any attempt to use  `devout::ascii()` or `devout::verbose()` results in an immediate hard crash.

The actual Appveyor crash report in `failure.zip` is not very informative, so I'm not too sure on what the next steps might be to fix this.

**Comment by mdsumner** [comment]
I print-debugged my way in as far as rcallback: 

![image](https://user-images.githubusercontent.com/4107631/66829834-ed34a680-ef9f-11e9-979c-7a8e55e9c289.png)

**Comment by mdequeljoe** [comment]
I've come across this issue as well on a windows station.

When I change these two lines in `rdevice_open`:

https://github.com/coolbutuseless/devout/blob/5c6835794149d5c973c2812bca7d6bfc9df66f71/src/rdevice.cpp#L1669-L1670

to:

```C++
 cdata_struct *cdata = new cdata_struct;
```

then the following works (or I should say doesn't seg fault):
```R
library(devout)
verbose()
```

**Comment by coolbutuseless** [comment]
Doesn't segfault!  I'll count that as a win!

Do you get any sane output if you do the following?

```
  devout::verbose()
  plot(1:10)
  invisible(dev.off())
```

**Comment by coolbutuseless** [comment]
Just switched the 'cdata' allocation from calloc/free to new/delete and now the AppVeyor windows build works! Thanks @mdequeljoe
