### ISSUE TITLE
Avoid need to have devout loaded

### ISSUE THREAD

**Issue by thomasp85** [coolbutuseless/devout#5]
Currently, for reasons I can't fully understand, devout has to be loaded and attached, meaning packages using it needs to have devout in their `Depends` field. This may be related to #4, but I don't fully understand the dispatch so I'm not sure

**Comment by coolbutuseless** [comment]
Explanation:  Within Rcpp, I was asking for the package using the equivalent of `as.environment("package:devout")`.  I've now changed this to the equivalent of `asNamespace('devout')`.

This seems to fix the issue of having to have `{devout}` loaded and attached.

Please re-open if this is still an issue.
