### ISSUE TITLE
state$rdata should be an environment

### ISSUE THREAD

**Issue by thomasp85** [coolbutuseless/devout#6]
changes to `state$rdata` by the callback functions may get lost due to R's copy on modify semantics. This would be solved if the `rdata` element was an environment instead

**Comment by coolbutuseless** [comment]
Agreed.

**Comment by coolbutuseless** [comment]
I've switched 'rdata' over from a list to an environment.  I think this means I can drop some other manual caching I was doing in `rdevice.R` but haven't sorted that yet.
